"""Deterministic train/val/calib/test assignment.

Lives here rather than in either the simulator or the loader because both need
it and neither should depend on the other. Having generation pick a random split
and loading override it with a different rule is two mechanisms for one decision,
and the two can disagree.

**Four splits, not three.** ``calib`` exists solely so split-conformal
calibration has data the model was neither trained on *nor* selected on. Fitting
the conformal quantile on ``val`` — the split that chose the checkpoint — makes
the calibration scores optimistic: early stopping picks the epoch that fits
``val`` best, so ``1 - p(true class)`` is smaller there than on genuinely fresh
data, the quantile comes out too small, and the coverage the console advertises
is not the coverage it delivers. Exchangeability between the calibration set and
the points being scored is the one assumption conformal prediction makes, and
model selection on the calibration set breaks it.

The band is carved out of the old ``val`` range rather than taken from the ends,
so **train and test membership are byte-identical to the previous rule** and any
metric measured on ``test`` stays comparable across the change.
"""

from __future__ import annotations

import hashlib

#: (train, calib, val, test) — note the order. The old rule was
#: (0.70, 0.15, 0.15) for train/val/test; the former val band is split down the
#: middle, leaving the train and test bands untouched.
#:
#: `calib` takes the *first* half of that band and `val` the second. The order
#: was chosen knowing where it put one machine, so it is stated rather than
#: buried: when the training fleet recorded only each machine's first 800
#: throws, 11 of 64 machines reached a failure and exactly one of them (PMD052)
#: fell in this band. A conformal RUL interval needs uncensored targets and
#: early stopping does not — it selects on macro-F1 — so the band was ordered to
#: give that machine to `calib`.
#:
#: Since RP-26 the fleet simulates whole service lives, and `calib` receives 4
#: failing machines out of 5 on its own merits. The order no longer decides
#: whether an interval can be fitted, and is kept so the split stays stable.
DEFAULT_FRACS = (0.70, 0.075, 0.075, 0.15)
SALT = "railpoint-v1"


def machine_split(
    machine_id: str,
    fracs: tuple[float, float, float, float] = DEFAULT_FRACS,
    salt: str = SALT,
) -> str:
    """Assign a machine to train/calib/val/test from its id alone.

    The fleet and stratified datasets are generated by separate RNG streams, so
    if each picked its own splits a machine could land in stratified-train and
    fleet-test - and training on both would leak. Hashing the id makes the
    assignment identical everywhere, for any dataset, in any order, forever.

    Splitting by *machine* rather than by event is what keeps the assignment
    honest: consecutive throws of one machine are near-duplicates, so an
    event-level split would put a window's own neighbours on the other side and
    report a score that means nothing.
    """
    digest = hashlib.sha256(f"{salt}:{machine_id}".encode()).hexdigest()[:8]
    u = int(digest, 16) / 0xFFFFFFFF
    train, calib, val = fracs[0], fracs[1], fracs[2]
    if u < train:
        return "train"
    if u < train + calib:
        return "calib"
    return "val" if u < train + calib + val else "test"
