"""Deterministic train/val/test assignment.

Lives here rather than in either the simulator or the loader because both need
it and neither should depend on the other. Having generation pick a random split
and loading override it with a different rule is two mechanisms for one decision,
and the two can disagree.
"""

from __future__ import annotations

import hashlib

DEFAULT_FRACS = (0.70, 0.15, 0.15)
SALT = "railpoint-v1"


def machine_split(
    machine_id: str,
    fracs: tuple[float, float, float] = DEFAULT_FRACS,
    salt: str = SALT,
) -> str:
    """Assign a machine to train/val/test from its id alone.

    The fleet and stratified datasets are generated by separate RNG streams, so
    if each picked its own splits a machine could land in stratified-train and
    fleet-test - and training on both would leak. Hashing the id makes the
    assignment identical everywhere, for any dataset, in any order, forever.
    """
    digest = hashlib.sha256(f"{salt}:{machine_id}".encode()).hexdigest()[:8]
    u = int(digest, 16) / 0xFFFFFFFF
    if u < fracs[0]:
        return "train"
    return "val" if u < fracs[0] + fracs[1] else "test"
